client:
  draft_model: models/Qwen3-0.6B-GGUF/Qwen3-0.6B-Q4_0.gguf
  n_gpu_layers: -1
  main_gpu: 0
  n_threads: null
  n_threads_batch: null
  host: mango1:8000
  dtype: fp16
  max_len: 2048
  max_n_beams: 4
  max_beam_len: 8
  max_branch_width: 2
  max_budget: 16
  max_seqs: null
  max_new_tokens: 64
  client_idx: 0
  dataset: specbench
  reasoning: false
  max_request_num: -1
  req_offset: 0
  sample_req_cnt: 8
