// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: specedge.proto
// Protobuf C++ Version: 7.36.0

#include "specedge.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::specedge::ValidateRequest
        {&::_pbi::kDescriptorMethods, &::descriptor_table_specedge_2eproto, /* tracker*/ nullptr,},
        // ::specedge::ValidateResponse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_specedge_2eproto, /* tracker*/ nullptr,},
        // ::specedge::SyncRequest
        {&::_pbi::kDescriptorMethods, &::descriptor_table_specedge_2eproto, /* tracker*/ nullptr,},
        // ::specedge::SyncResponse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_specedge_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace specedge {
class ValidateResponse::_Internal {
 public:
  using HasBits = decltype(::std::declval<ValidateResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_._has_bits_);
};

constexpr ValidateResponse::ParseTableT_ ValidateResponse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::specedge::ValidateResponse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // int32 prefill = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ValidateResponse, _impl_.prefill_), 1>(),
       {16, 1, 0,
        PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_.prefill_)}},
      // bytes selection = 1;
      {::_pbi::TcParser::FastBS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_.selection_)}},
    }}, {{
      65535, 65535
    }}, {{
      // bytes selection = 1;
      {PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_.selection_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // int32 prefill = 2;
      {PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_.prefill_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr ValidateResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : selection_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        prefill_{0} {}

template <typename>
constexpr ValidateResponse::ValidateResponse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL ValidateResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ValidateResponse(arena);
}
constexpr auto ValidateResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ValidateResponse), alignof(ValidateResponse));
}
constexpr auto ValidateResponse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &ValidateResponse::MergeImpl,
          Super_::GetNewImpl<ValidateResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ValidateResponse::SharedDtor,
          Super_::GetClearImpl<ValidateResponse>(), &ValidateResponse::ByteSizeLong,
              &ValidateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ValidateResponse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_specedge_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct ValidateResponseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr ValidateResponseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 ValidateResponse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(ValidateResponse::InternalGenerateClassData_(
            _default, &ValidateResponse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<ValidateResponse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~ValidateResponseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) ValidateResponse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<ValidateResponse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(ValidateResponseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST ValidateResponseGlobalsTypeInternal ValidateResponse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* ValidateResponse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ValidateResponse_globals_.GetClassData();
#else
  return ValidateResponse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class ValidateRequest::_Internal {
 public:
  using HasBits = decltype(::std::declval<ValidateRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_._has_bits_);
};

constexpr ValidateRequest::ParseTableT_ ValidateRequest::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_._has_bits_),
      0, // no _extensions_
      9, 120,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294966784,  // skipmap
      offsetof(ParseTableT_, field_entries),
      9,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::specedge::ValidateRequest>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // int32 client_idx = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ValidateRequest, _impl_.client_idx_), 6>(),
       {8, 6, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.client_idx_)}},
      // int32 req_idx = 2;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ValidateRequest, _impl_.req_idx_), 7>(),
       {16, 7, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.req_idx_)}},
      // bytes input_ids = 3;
      {::_pbi::TcParser::FastBS1,
       {26, 0, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.input_ids_)}},
      // bytes position_ids = 4;
      {::_pbi::TcParser::FastBS1,
       {34, 1, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.position_ids_)}},
      // bytes cache_seq_indices = 5;
      {::_pbi::TcParser::FastBS1,
       {42, 2, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.cache_seq_indices_)}},
      // bytes parent_indices = 6;
      {::_pbi::TcParser::FastBS1,
       {50, 3, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.parent_indices_)}},
      // bytes attention_mask = 7;
      {::_pbi::TcParser::FastBS1,
       {58, 4, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.attention_mask_)}},
      // bool prefill = 8;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ValidateRequest, _impl_.prefill_), 8>(),
       {64, 8, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.prefill_)}},
      // optional string prefix = 9;
      {::_pbi::TcParser::FastUS1,
       {74, 5, 0,
        PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.prefix_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 client_idx = 1;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.client_idx_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 req_idx = 2;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.req_idx_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // bytes input_ids = 3;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.input_ids_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bytes position_ids = 4;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.position_ids_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bytes cache_seq_indices = 5;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.cache_seq_indices_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bytes parent_indices = 6;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.parent_indices_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bytes attention_mask = 7;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.attention_mask_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bool prefill = 8;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.prefill_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // optional string prefix = 9;
      {PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.prefix_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\30\0\0\0\0\0\0\0\0\6\0\0\0\0\0\0"
      "specedge.ValidateRequest"
      "prefix"
    }},
  };
}


inline constexpr ValidateRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : input_ids_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_ids_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cache_seq_indices_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        parent_indices_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        attention_mask_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        prefix_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        client_idx_{0},
        req_idx_{0},
        prefill_{false} {}

template <typename>
constexpr ValidateRequest::ValidateRequest(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL ValidateRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ValidateRequest(arena);
}
constexpr auto ValidateRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ValidateRequest), alignof(ValidateRequest));
}
constexpr auto ValidateRequest::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &ValidateRequest::MergeImpl,
          Super_::GetNewImpl<ValidateRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ValidateRequest::SharedDtor,
          Super_::GetClearImpl<ValidateRequest>(), &ValidateRequest::ByteSizeLong,
              &ValidateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_specedge_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct ValidateRequestGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr ValidateRequestGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 ValidateRequest_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(ValidateRequest::InternalGenerateClassData_(
            _default, &ValidateRequest_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<ValidateRequest>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~ValidateRequestGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) ValidateRequest _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<ValidateRequest>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(ValidateRequestGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST ValidateRequestGlobalsTypeInternal ValidateRequest_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* ValidateRequest_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ValidateRequest_globals_.GetClassData();
#else
  return ValidateRequest_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SyncResponse::_Internal {
 public:
};

constexpr SyncResponse::ParseTableT_ SyncResponse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SyncResponse,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::specedge::SyncResponse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SyncResponse::SyncResponse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SyncResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SyncResponse(arena);
}
constexpr auto SyncResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SyncResponse), alignof(SyncResponse));
}
constexpr auto SyncResponse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SyncResponse::MergeImpl,
          Super_::GetNewImpl<SyncResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SyncResponse::SharedDtor,
          Super_::GetClearImpl<SyncResponse>(), &SyncResponse::ByteSizeLong,
              &SyncResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_specedge_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SyncResponseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SyncResponseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SyncResponse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SyncResponse::InternalGenerateClassData_(
            _default, &SyncResponse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SyncResponse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SyncResponseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SyncResponse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SyncResponse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SyncResponseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SyncResponseGlobalsTypeInternal SyncResponse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SyncResponse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SyncResponse_globals_.GetClassData();
#else
  return SyncResponse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SyncRequest::_Internal {
 public:
};

constexpr SyncRequest::ParseTableT_ SyncRequest::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SyncRequest,
                            _impl_._cached_size_),  // no hasbits
      0, // no _extensions_
      0, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967295,  // skipmap
      offsetof(ParseTableT_, field_names),  // no field_entries
      0,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::specedge::SyncRequest>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, // no field_entries, or aux_entries
    {{
    }},
  };
}

template <typename>
constexpr SyncRequest::SyncRequest(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL SyncRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SyncRequest(arena);
}
constexpr auto SyncRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SyncRequest), alignof(SyncRequest));
}
constexpr auto SyncRequest::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SyncRequest::MergeImpl,
          Super_::GetNewImpl<SyncRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SyncRequest::SharedDtor,
          Super_::GetClearImpl<SyncRequest>(), &SyncRequest::ByteSizeLong,
              &SyncRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_specedge_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct SyncRequestGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SyncRequestGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SyncRequest_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SyncRequest::InternalGenerateClassData_(
            _default, &SyncRequest_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SyncRequest>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SyncRequestGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SyncRequest _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SyncRequest>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SyncRequestGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SyncRequestGlobalsTypeInternal SyncRequest_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SyncRequest_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SyncRequest_globals_.GetClassData();
#else
  return SyncRequest_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace specedge
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_specedge_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_specedge_2eproto = nullptr;
const ::uint32_t
    TableStruct_specedge_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.client_idx_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.req_idx_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.input_ids_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.position_ids_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.cache_seq_indices_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.parent_indices_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.attention_mask_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.prefill_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateRequest, _impl_.prefix_),
        6,
        7,
        0,
        1,
        2,
        3,
        4,
        8,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateResponse, _impl_.selection_),
        PROTOBUF_FIELD_OFFSET(::specedge::ValidateResponse, _impl_.prefill_),
        0,
        1,
        0x000, // bitmap
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::specedge::ValidateRequest)},
        {21, sizeof(::specedge::ValidateResponse)},
        {28, sizeof(::specedge::SyncRequest)},
        {29, sizeof(::specedge::SyncResponse)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::specedge::ValidateRequest_globals_,
        &::specedge::ValidateResponse_globals_,
        &::specedge::SyncRequest_globals_,
        &::specedge::SyncResponse_globals_,
};
const char descriptor_table_protodef_specedge_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016specedge.proto\022\010specedge\"\333\001\n\017ValidateR"
    "equest\022\022\n\nclient_idx\030\001 \001(\005\022\017\n\007req_idx\030\002 "
    "\001(\005\022\021\n\tinput_ids\030\003 \001(\014\022\024\n\014position_ids\030\004"
    " \001(\014\022\031\n\021cache_seq_indices\030\005 \001(\014\022\026\n\016paren"
    "t_indices\030\006 \001(\014\022\026\n\016attention_mask\030\007 \001(\014\022"
    "\017\n\007prefill\030\010 \001(\010\022\023\n\006prefix\030\t \001(\tH\000\210\001\001B\t\n"
    "\007_prefix\"6\n\020ValidateResponse\022\021\n\tselectio"
    "n\030\001 \001(\014\022\017\n\007prefill\030\002 \001(\005\"\r\n\013SyncRequest\""
    "\016\n\014SyncResponse2\217\001\n\017SpecEdgeService\022C\n\010V"
    "alidate\022\031.specedge.ValidateRequest\032\032.spe"
    "cedge.ValidateResponse\"\000\0227\n\004Sync\022\025.spece"
    "dge.SyncRequest\032\026.specedge.SyncResponse\""
    "\000b\006proto3"
};
static ::absl::once_flag descriptor_table_specedge_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_specedge_2eproto = {
    false,
    false,
    489,
    descriptor_table_protodef_specedge_2eproto,
    "specedge.proto",
    &descriptor_table_specedge_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_message_globals,
    TableStruct_specedge_2eproto::offsets,
    file_level_enum_descriptors_specedge_2eproto,
    file_level_service_descriptors_specedge_2eproto,
};
namespace specedge {
// ===================================================================

ValidateRequest::ValidateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, ValidateRequest_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:specedge.ValidateRequest)
}
PROTOBUF_NDEBUG_INLINE ValidateRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::specedge::ValidateRequest& from_msg)
      : _has_bits_{from._has_bits_},
        input_ids_(arena, from.input_ids_),
        position_ids_(arena, from.position_ids_),
        cache_seq_indices_(arena, from.cache_seq_indices_),
        parent_indices_(arena, from.parent_indices_),
        attention_mask_(arena, from.attention_mask_),
        prefix_(arena, from.prefix_) {}

ValidateRequest::ValidateRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ValidateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, ValidateRequest_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ValidateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, client_idx_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, client_idx_),
           offsetof(Impl_, prefill_) -
               offsetof(Impl_, client_idx_) +
               sizeof(Impl_::prefill_));

  // @@protoc_insertion_point(copy_constructor:specedge.ValidateRequest)
}
PROTOBUF_NDEBUG_INLINE ValidateRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : input_ids_(arena),
        position_ids_(arena),
        cache_seq_indices_(arena),
        parent_indices_(arena),
        attention_mask_(arena),
        prefix_(arena) {}

inline void ValidateRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, client_idx_),
           0,
           offsetof(Impl_, prefill_) -
               offsetof(Impl_, client_idx_) +
               sizeof(Impl_::prefill_));
}
ValidateRequest::~ValidateRequest() {
  // @@protoc_insertion_point(destructor:specedge.ValidateRequest)
  SharedDtor(*this);
}
inline void ValidateRequest::SharedDtor(MessageLite& self) {
  ValidateRequest& this_ = static_cast<ValidateRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.input_ids_.Destroy();
  this_._impl_.position_ids_.Destroy();
  this_._impl_.cache_seq_indices_.Destroy();
  this_._impl_.parent_indices_.Destroy();
  this_._impl_.attention_mask_.Destroy();
  this_._impl_.prefix_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ValidateRequest_class_data_ =
        ValidateRequest::InternalGenerateClassData_(ValidateRequest_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ValidateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ValidateRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ValidateRequest_class_data_.tc_table);
  return ValidateRequest_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ValidateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ValidateRequest_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&ValidateRequest_globals_));
  return ValidateRequest_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ValidateRequest::ParseTableT_
    ValidateRequest::_table_ =
        ValidateRequest::InternalGenerateParseTable_(ValidateRequest_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void ValidateRequest::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:specedge.ValidateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.input_ids_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.position_ids_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      this_._impl_.cache_seq_indices_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      this_._impl_.parent_indices_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      this_._impl_.attention_mask_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      this_._impl_.prefix_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000c0U)) {
    ::memset(&this_._impl_.client_idx_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.req_idx_) -
                 reinterpret_cast<char*>(&this_._impl_.client_idx_)) +
                 sizeof(_impl_.req_idx_));
  }
  this_._impl_.prefill_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ValidateRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ValidateRequest& this_ = static_cast<const ValidateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ValidateRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ValidateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:specedge.ValidateRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 client_idx = 1;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_client_idx() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_client_idx(), target);
    }
  }

  // int32 req_idx = 2;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_req_idx() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_req_idx(), target);
    }
  }

  // bytes input_ids = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_input_ids().empty()) {
      const ::std::string& _s = this_._internal_input_ids();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bytes position_ids = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_position_ids().empty()) {
      const ::std::string& _s = this_._internal_position_ids();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  // bytes cache_seq_indices = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_cache_seq_indices().empty()) {
      const ::std::string& _s = this_._internal_cache_seq_indices();
      target = stream->WriteBytesMaybeAliased(5, _s, target);
    }
  }

  // bytes parent_indices = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_parent_indices().empty()) {
      const ::std::string& _s = this_._internal_parent_indices();
      target = stream->WriteBytesMaybeAliased(6, _s, target);
    }
  }

  // bytes attention_mask = 7;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_attention_mask().empty()) {
      const ::std::string& _s = this_._internal_attention_mask();
      target = stream->WriteBytesMaybeAliased(7, _s, target);
    }
  }

  // bool prefill = 8;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_prefill() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          8, this_._internal_prefill(), target);
    }
  }

  // optional string prefix = 9;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    const ::std::string& _s = this_._internal_prefix();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "specedge.ValidateRequest.prefix");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:specedge.ValidateRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ValidateRequest::ByteSizeLong(const MessageLite& base) {
  const ValidateRequest& this_ = static_cast<const ValidateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ValidateRequest::ByteSizeLong() const {
  const ValidateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:specedge.ValidateRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // bytes input_ids = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_input_ids().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_input_ids());
      }
    }
    // bytes position_ids = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_position_ids().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_position_ids());
      }
    }
    // bytes cache_seq_indices = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_cache_seq_indices().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_cache_seq_indices());
      }
    }
    // bytes parent_indices = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_parent_indices().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_parent_indices());
      }
    }
    // bytes attention_mask = 7;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_attention_mask().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_attention_mask());
      }
    }
    // optional string prefix = 9;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_prefix());
    }
    // int32 client_idx = 1;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_client_idx() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_client_idx());
      }
    }
    // int32 req_idx = 2;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_req_idx() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_req_idx());
      }
    }
  }
   {
    // bool prefill = 8;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_prefill() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ValidateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<ValidateRequest*>(&to_msg);
  auto& from = static_cast<const ValidateRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:specedge.ValidateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_input_ids().empty()) {
        _this->_internal_set_input_ids(from._internal_input_ids());
      } else {
        if (_this->_impl_.input_ids_.IsDefault()) {
          _this->_internal_set_input_ids("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_position_ids().empty()) {
        _this->_internal_set_position_ids(from._internal_position_ids());
      } else {
        if (_this->_impl_.position_ids_.IsDefault()) {
          _this->_internal_set_position_ids("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_cache_seq_indices().empty()) {
        _this->_internal_set_cache_seq_indices(from._internal_cache_seq_indices());
      } else {
        if (_this->_impl_.cache_seq_indices_.IsDefault()) {
          _this->_internal_set_cache_seq_indices("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_parent_indices().empty()) {
        _this->_internal_set_parent_indices(from._internal_parent_indices());
      } else {
        if (_this->_impl_.parent_indices_.IsDefault()) {
          _this->_internal_set_parent_indices("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_attention_mask().empty()) {
        _this->_internal_set_attention_mask(from._internal_attention_mask());
      } else {
        if (_this->_impl_.attention_mask_.IsDefault()) {
          _this->_internal_set_attention_mask("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_internal_set_prefix(from._internal_prefix());
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_client_idx() != 0) {
        _this->_impl_.client_idx_ = from._impl_.client_idx_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_req_idx() != 0) {
        _this->_impl_.req_idx_ = from._impl_.req_idx_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (from._internal_prefill() != 0) {
      _this->_impl_.prefill_ = from._impl_.prefill_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ValidateRequest::CopyFrom(const ValidateRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:specedge.ValidateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidateRequest::InternalSwap(ValidateRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.input_ids_, &other->_impl_.input_ids_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.position_ids_, &other->_impl_.position_ids_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cache_seq_indices_, &other->_impl_.cache_seq_indices_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parent_indices_, &other->_impl_.parent_indices_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.attention_mask_, &other->_impl_.attention_mask_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.prefix_, &other->_impl_.prefix_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.prefill_)
      + sizeof(ValidateRequest::_impl_.prefill_)
      - PROTOBUF_FIELD_OFFSET(ValidateRequest, _impl_.client_idx_)>(
          reinterpret_cast<char*>(&_impl_.client_idx_),
          reinterpret_cast<char*>(&other->_impl_.client_idx_));
}

::google::protobuf::Metadata ValidateRequest::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

ValidateResponse::ValidateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, ValidateResponse_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:specedge.ValidateResponse)
}
PROTOBUF_NDEBUG_INLINE ValidateResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::specedge::ValidateResponse& from_msg)
      : _has_bits_{from._has_bits_},
        selection_(arena, from.selection_) {}

ValidateResponse::ValidateResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ValidateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, ValidateResponse_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ValidateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.prefill_ = from._impl_.prefill_;

  // @@protoc_insertion_point(copy_constructor:specedge.ValidateResponse)
}
PROTOBUF_NDEBUG_INLINE ValidateResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : selection_(arena) {}

inline void ValidateResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.prefill_ = {};
}
ValidateResponse::~ValidateResponse() {
  // @@protoc_insertion_point(destructor:specedge.ValidateResponse)
  SharedDtor(*this);
}
inline void ValidateResponse::SharedDtor(MessageLite& self) {
  ValidateResponse& this_ = static_cast<ValidateResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.selection_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ValidateResponse_class_data_ =
        ValidateResponse::InternalGenerateClassData_(ValidateResponse_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ValidateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ValidateResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ValidateResponse_class_data_.tc_table);
  return ValidateResponse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ValidateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ValidateResponse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&ValidateResponse_globals_));
  return ValidateResponse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ValidateResponse::ParseTableT_
    ValidateResponse::_table_ =
        ValidateResponse::InternalGenerateParseTable_(ValidateResponse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void ValidateResponse::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:specedge.ValidateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    this_._impl_.selection_.ClearNonDefaultToEmpty();
  }
  this_._impl_.prefill_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ValidateResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ValidateResponse& this_ = static_cast<const ValidateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ValidateResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ValidateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:specedge.ValidateResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes selection = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_selection().empty()) {
      const ::std::string& _s = this_._internal_selection();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // int32 prefill = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_prefill() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_prefill(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:specedge.ValidateResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ValidateResponse::ByteSizeLong(const MessageLite& base) {
  const ValidateResponse& this_ = static_cast<const ValidateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ValidateResponse::ByteSizeLong() const {
  const ValidateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:specedge.ValidateResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes selection = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_selection().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_selection());
      }
    }
    // int32 prefill = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_prefill() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_prefill());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ValidateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<ValidateResponse*>(&to_msg);
  auto& from = static_cast<const ValidateResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:specedge.ValidateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_selection().empty()) {
        _this->_internal_set_selection(from._internal_selection());
      } else {
        if (_this->_impl_.selection_.IsDefault()) {
          _this->_internal_set_selection("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_prefill() != 0) {
        _this->_impl_.prefill_ = from._impl_.prefill_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ValidateResponse::CopyFrom(const ValidateResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:specedge.ValidateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ValidateResponse::InternalSwap(ValidateResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.selection_, &other->_impl_.selection_, arena);
  swap(_impl_.prefill_, other->_impl_.prefill_);
}

::google::protobuf::Metadata ValidateResponse::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SyncRequest::SyncRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SyncRequest_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:specedge.SyncRequest)
}
SyncRequest::SyncRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SyncRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SyncRequest_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:specedge.SyncRequest)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SyncRequest_class_data_ =
        SyncRequest::InternalGenerateClassData_(SyncRequest_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SyncRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SyncRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SyncRequest_class_data_.tc_table);
  return SyncRequest_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SyncRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SyncRequest_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SyncRequest_globals_));
  return SyncRequest_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SyncRequest::ParseTableT_
    SyncRequest::_table_ =
        SyncRequest::InternalGenerateParseTable_(SyncRequest_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SyncRequest::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

SyncResponse::SyncResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SyncResponse_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:specedge.SyncResponse)
}
SyncResponse::SyncResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SyncResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SyncResponse_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:specedge.SyncResponse)
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SyncResponse_class_data_ =
        SyncResponse::InternalGenerateClassData_(SyncResponse_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SyncResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SyncResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SyncResponse_class_data_.tc_table);
  return SyncResponse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SyncResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SyncResponse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&SyncResponse_globals_));
  return SyncResponse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SyncResponse::ParseTableT_
    SyncResponse::_table_ =
        SyncResponse::InternalGenerateParseTable_(SyncResponse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS







::google::protobuf::Metadata SyncResponse::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace specedge
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_specedge_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
