// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: specedge.proto
// Protobuf C++ Version: 7.36.0

#ifndef specedge_2eproto_2epb_2eh
#define specedge_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_specedge_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_specedge_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_specedge_2eproto;
}  // extern "C"
namespace specedge {
class SyncRequest;
struct SyncRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SyncRequestGlobalsTypeInternal SyncRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull SyncRequest_class_data_;
#else
extern const SyncRequestGlobalsTypeInternal SyncRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class SyncResponse;
struct SyncResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SyncResponseGlobalsTypeInternal SyncResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull SyncResponse_class_data_;
#else
extern const SyncResponseGlobalsTypeInternal SyncResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class ValidateRequest;
struct ValidateRequestGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern ValidateRequestGlobalsTypeInternal ValidateRequest_globals_;
extern const ::google::protobuf::internal::ClassDataFull ValidateRequest_class_data_;
#else
extern const ValidateRequestGlobalsTypeInternal ValidateRequest_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class ValidateResponse;
struct ValidateResponseGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern ValidateResponseGlobalsTypeInternal ValidateResponse_globals_;
extern const ::google::protobuf::internal::ClassDataFull ValidateResponse_class_data_;
#else
extern const ValidateResponseGlobalsTypeInternal ValidateResponse_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace specedge
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace specedge {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ValidateResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:specedge.ValidateResponse) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline ValidateResponse() : ValidateResponse(nullptr) {}
  ~ValidateResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ValidateResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ValidateResponse));
  }
#endif

  template <typename = void>
  explicit constexpr ValidateResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline ValidateResponse(const ValidateResponse& from) : ValidateResponse(nullptr, from) {}
  inline ValidateResponse(ValidateResponse&& from) noexcept : ValidateResponse(nullptr, ::std::move(from)) {}
  inline ValidateResponse& operator=(const ValidateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ValidateResponse& operator=(ValidateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ValidateResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<ValidateResponse>(&ValidateResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ValidateResponse& a, ValidateResponse& b) { a.Swap(&b); }
  inline void Swap(ValidateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ValidateResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ValidateResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<ValidateResponse>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const ValidateResponse& from);
  using Super_::MergeFrom;
  void MergeFrom(const ValidateResponse& from) { ValidateResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ValidateResponse* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "specedge.ValidateResponse"; }

  explicit ValidateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ValidateResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ValidateResponse& from);
  ValidateResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ValidateResponse&& from) noexcept
      : ValidateResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSelectionFieldNumber = 1,
    kPrefillFieldNumber = 2,
  };
  // bytes selection = 1;
  void clear_selection() ;
  [[nodiscard]] const ::std::string& selection() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_selection(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_selection();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_selection();
  void set_allocated_selection(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_selection() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_selection(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_selection();

  public:
  // int32 prefill = 2;
  void clear_prefill() ;
  [[nodiscard]] ::int32_t prefill() const;
  void set_prefill(::int32_t value);

  private:
  ::int32_t _internal_prefill() const;
  void _internal_set_prefill(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:specedge.ValidateResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ValidateResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr selection_;
    ::int32_t prefill_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_specedge_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ValidateRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:specedge.ValidateRequest) */ {
  using Super_ = ::google::protobuf::Message;

 public:
  inline ValidateRequest() : ValidateRequest(nullptr) {}
  ~ValidateRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ValidateRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ValidateRequest));
  }
#endif

  template <typename = void>
  explicit constexpr ValidateRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline ValidateRequest(const ValidateRequest& from) : ValidateRequest(nullptr, from) {}
  inline ValidateRequest(ValidateRequest&& from) noexcept : ValidateRequest(nullptr, ::std::move(from)) {}
  inline ValidateRequest& operator=(const ValidateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ValidateRequest& operator=(ValidateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ValidateRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<ValidateRequest>(&ValidateRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ValidateRequest& a, ValidateRequest& b) { a.Swap(&b); }
  inline void Swap(ValidateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ValidateRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ValidateRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<ValidateRequest>(arena);
  }
  using Super_::CopyFrom;
  void CopyFrom(const ValidateRequest& from);
  using Super_::MergeFrom;
  void MergeFrom(const ValidateRequest& from) { ValidateRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ValidateRequest* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "specedge.ValidateRequest"; }

  explicit ValidateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ValidateRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ValidateRequest& from);
  ValidateRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ValidateRequest&& from) noexcept
      : ValidateRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInputIdsFieldNumber = 3,
    kPositionIdsFieldNumber = 4,
    kCacheSeqIndicesFieldNumber = 5,
    kParentIndicesFieldNumber = 6,
    kAttentionMaskFieldNumber = 7,
    kPrefixFieldNumber = 9,
    kClientIdxFieldNumber = 1,
    kReqIdxFieldNumber = 2,
    kPrefillFieldNumber = 8,
  };
  // bytes input_ids = 3;
  void clear_input_ids() ;
  [[nodiscard]] const ::std::string& input_ids() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_input_ids(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_input_ids();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_input_ids();
  void set_allocated_input_ids(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_input_ids() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_input_ids(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_input_ids();

  public:
  // bytes position_ids = 4;
  void clear_position_ids() ;
  [[nodiscard]] const ::std::string& position_ids() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_position_ids(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_position_ids();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_position_ids();
  void set_allocated_position_ids(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_position_ids() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_position_ids(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_position_ids();

  public:
  // bytes cache_seq_indices = 5;
  void clear_cache_seq_indices() ;
  [[nodiscard]] const ::std::string& cache_seq_indices() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cache_seq_indices(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cache_seq_indices();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cache_seq_indices();
  void set_allocated_cache_seq_indices(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cache_seq_indices() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cache_seq_indices(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cache_seq_indices();

  public:
  // bytes parent_indices = 6;
  void clear_parent_indices() ;
  [[nodiscard]] const ::std::string& parent_indices() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_parent_indices(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_parent_indices();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_parent_indices();
  void set_allocated_parent_indices(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_parent_indices() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_parent_indices(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_parent_indices();

  public:
  // bytes attention_mask = 7;
  void clear_attention_mask() ;
  [[nodiscard]] const ::std::string& attention_mask() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_attention_mask(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_attention_mask();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_attention_mask();
  void set_allocated_attention_mask(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_attention_mask() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_attention_mask(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_attention_mask();

  public:
  // optional string prefix = 9;
  [[nodiscard]] bool has_prefix() const;
  void clear_prefix() ;
  [[nodiscard]] const ::std::string& prefix() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_prefix(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_prefix();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_prefix();
  void set_allocated_prefix(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_prefix() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_prefix(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_prefix();

  public:
  // int32 client_idx = 1;
  void clear_client_idx() ;
  [[nodiscard]] ::int32_t client_idx() const;
  void set_client_idx(::int32_t value);

  private:
  ::int32_t _internal_client_idx() const;
  void _internal_set_client_idx(::int32_t value);

  public:
  // int32 req_idx = 2;
  void clear_req_idx() ;
  [[nodiscard]] ::int32_t req_idx() const;
  void set_req_idx(::int32_t value);

  private:
  ::int32_t _internal_req_idx() const;
  void _internal_set_req_idx(::int32_t value);

  public:
  // bool prefill = 8;
  void clear_prefill() ;
  [[nodiscard]] bool prefill() const;
  void set_prefill(bool value);

  private:
  bool _internal_prefill() const;
  void _internal_set_prefill(bool value);

  public:
  // @@protoc_insertion_point(class_scope:specedge.ValidateRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 9,
                          0, 47,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ValidateRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr input_ids_;
    ::google::protobuf::internal::ArenaStringPtr position_ids_;
    ::google::protobuf::internal::ArenaStringPtr cache_seq_indices_;
    ::google::protobuf::internal::ArenaStringPtr parent_indices_;
    ::google::protobuf::internal::ArenaStringPtr attention_mask_;
    ::google::protobuf::internal::ArenaStringPtr prefix_;
    ::int32_t client_idx_;
    ::int32_t req_idx_;
    bool prefill_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_specedge_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SyncResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:specedge.SyncResponse) */ {
  using Super_ = ::google::protobuf::internal::ZeroFieldsBase;

 public:
  inline SyncResponse() : SyncResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SyncResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SyncResponse));
  }
#endif

  template <typename = void>
  explicit constexpr SyncResponse(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SyncResponse(const SyncResponse& from) : SyncResponse(nullptr, from) {}
  inline SyncResponse(SyncResponse&& from) noexcept : SyncResponse(nullptr, ::std::move(from)) {}
  inline SyncResponse& operator=(const SyncResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncResponse& operator=(SyncResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const SyncResponse& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SyncResponse>(&SyncResponse_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SyncResponse& a, SyncResponse& b) { a.Swap(&b); }
  inline void Swap(SyncResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SyncResponse* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SyncResponse>(arena);
  }
  using Super_::CopyFrom;
  inline void CopyFrom(const SyncResponse& from) { Super_::CopyImpl(*this, from); }
  using Super_::MergeFrom;
  void MergeFrom(const SyncResponse& from) { Super_::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  static ::absl::string_view FullMessageName() { return "specedge.SyncResponse"; }

  explicit SyncResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SyncResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SyncResponse& from);
  SyncResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SyncResponse&& from) noexcept
      : SyncResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:specedge.SyncResponse)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_specedge_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SyncRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:specedge.SyncRequest) */ {
  using Super_ = ::google::protobuf::internal::ZeroFieldsBase;

 public:
  inline SyncRequest() : SyncRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SyncRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SyncRequest));
  }
#endif

  template <typename = void>
  explicit constexpr SyncRequest(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SyncRequest(const SyncRequest& from) : SyncRequest(nullptr, from) {}
  inline SyncRequest(SyncRequest&& from) noexcept : SyncRequest(nullptr, ::std::move(from)) {}
  inline SyncRequest& operator=(const SyncRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncRequest& operator=(SyncRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const SyncRequest& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SyncRequest>(&SyncRequest_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SyncRequest& a, SyncRequest& b) { a.Swap(&b); }
  inline void Swap(SyncRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SyncRequest* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SyncRequest>(arena);
  }
  using Super_::CopyFrom;
  inline void CopyFrom(const SyncRequest& from) { Super_::CopyImpl(*this, from); }
  using Super_::MergeFrom;
  void MergeFrom(const SyncRequest& from) { Super_::MergeImpl(*this, from); }

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
 private:
  static ::absl::string_view FullMessageName() { return "specedge.SyncRequest"; }

  explicit SyncRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SyncRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SyncRequest& from);
  SyncRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SyncRequest&& from) noexcept
      : SyncRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:specedge.SyncRequest)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 0,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_specedge_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ValidateRequest

// int32 client_idx = 1;
inline void ValidateRequest::clear_client_idx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_idx_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::int32_t ValidateRequest::client_idx() const {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.client_idx)
  return _internal_client_idx();
}
inline void ValidateRequest::set_client_idx(::int32_t value) {
  _internal_set_client_idx(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.client_idx)
}
inline ::int32_t ValidateRequest::_internal_client_idx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_idx_;
}
inline void ValidateRequest::_internal_set_client_idx(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_idx_ = value;
}

// int32 req_idx = 2;
inline void ValidateRequest::clear_req_idx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.req_idx_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::int32_t ValidateRequest::req_idx() const {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.req_idx)
  return _internal_req_idx();
}
inline void ValidateRequest::set_req_idx(::int32_t value) {
  _internal_set_req_idx(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.req_idx)
}
inline ::int32_t ValidateRequest::_internal_req_idx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.req_idx_;
}
inline void ValidateRequest::_internal_set_req_idx(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.req_idx_ = value;
}

// bytes input_ids = 3;
inline void ValidateRequest::clear_input_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_ids_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& ValidateRequest::input_ids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.input_ids)
  return _internal_input_ids();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_input_ids(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.input_ids_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.input_ids)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_input_ids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_input_ids();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.input_ids)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_input_ids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.input_ids_.Get();
}
inline void ValidateRequest::_internal_set_input_ids(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_ids_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_input_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.input_ids_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_input_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.input_ids)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.input_ids_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.input_ids_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_input_ids(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.input_ids_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.input_ids_.IsDefault()) {
    _impl_.input_ids_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.input_ids)
}

// bytes position_ids = 4;
inline void ValidateRequest::clear_position_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ids_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& ValidateRequest::position_ids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.position_ids)
  return _internal_position_ids();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_position_ids(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.position_ids_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.position_ids)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_position_ids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_position_ids();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.position_ids)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_position_ids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_ids_.Get();
}
inline void ValidateRequest::_internal_set_position_ids(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ids_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_position_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.position_ids_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_position_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.position_ids)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.position_ids_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.position_ids_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_position_ids(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.position_ids_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.position_ids_.IsDefault()) {
    _impl_.position_ids_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.position_ids)
}

// bytes cache_seq_indices = 5;
inline void ValidateRequest::clear_cache_seq_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_seq_indices_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& ValidateRequest::cache_seq_indices() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.cache_seq_indices)
  return _internal_cache_seq_indices();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_cache_seq_indices(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.cache_seq_indices_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.cache_seq_indices)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_cache_seq_indices()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_cache_seq_indices();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.cache_seq_indices)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_cache_seq_indices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cache_seq_indices_.Get();
}
inline void ValidateRequest::_internal_set_cache_seq_indices(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_seq_indices_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_cache_seq_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cache_seq_indices_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_cache_seq_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.cache_seq_indices)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.cache_seq_indices_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cache_seq_indices_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_cache_seq_indices(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.cache_seq_indices_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cache_seq_indices_.IsDefault()) {
    _impl_.cache_seq_indices_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.cache_seq_indices)
}

// bytes parent_indices = 6;
inline void ValidateRequest::clear_parent_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_indices_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& ValidateRequest::parent_indices() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.parent_indices)
  return _internal_parent_indices();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_parent_indices(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.parent_indices_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.parent_indices)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_parent_indices()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_parent_indices();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.parent_indices)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_parent_indices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parent_indices_.Get();
}
inline void ValidateRequest::_internal_set_parent_indices(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_indices_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_parent_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.parent_indices_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_parent_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.parent_indices)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.parent_indices_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.parent_indices_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_parent_indices(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.parent_indices_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.parent_indices_.IsDefault()) {
    _impl_.parent_indices_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.parent_indices)
}

// bytes attention_mask = 7;
inline void ValidateRequest::clear_attention_mask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attention_mask_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline const ::std::string& ValidateRequest::attention_mask() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.attention_mask)
  return _internal_attention_mask();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_attention_mask(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.attention_mask_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.attention_mask)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_attention_mask()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_attention_mask();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.attention_mask)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_attention_mask() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attention_mask_.Get();
}
inline void ValidateRequest::_internal_set_attention_mask(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attention_mask_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_attention_mask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.attention_mask_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_attention_mask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.attention_mask)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.attention_mask_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.attention_mask_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_attention_mask(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.attention_mask_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.attention_mask_.IsDefault()) {
    _impl_.attention_mask_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.attention_mask)
}

// bool prefill = 8;
inline void ValidateRequest::clear_prefill() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefill_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline bool ValidateRequest::prefill() const {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.prefill)
  return _internal_prefill();
}
inline void ValidateRequest::set_prefill(bool value) {
  _internal_set_prefill(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.prefill)
}
inline bool ValidateRequest::_internal_prefill() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prefill_;
}
inline void ValidateRequest::_internal_set_prefill(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefill_ = value;
}

// optional string prefix = 9;
inline bool ValidateRequest::has_prefix() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void ValidateRequest::clear_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline const ::std::string& ValidateRequest::prefix() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateRequest.prefix)
  return _internal_prefix();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateRequest::set_prefix(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.prefix_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateRequest.prefix)
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::mutable_prefix()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_prefix();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateRequest.prefix)
  return _s;
}
inline const ::std::string& ValidateRequest::_internal_prefix() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prefix_.Get();
}
inline void ValidateRequest::_internal_set_prefix(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateRequest::_internal_mutable_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prefix_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateRequest::release_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateRequest.prefix)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.prefix_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.prefix_.Set("", GetArena());
  }
  return released;
}
inline void ValidateRequest::set_allocated_prefix(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.prefix_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.prefix_.IsDefault()) {
    _impl_.prefix_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateRequest.prefix)
}

// -------------------------------------------------------------------

// ValidateResponse

// bytes selection = 1;
inline void ValidateResponse::clear_selection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selection_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& ValidateResponse::selection() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:specedge.ValidateResponse.selection)
  return _internal_selection();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ValidateResponse::set_selection(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.selection_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:specedge.ValidateResponse.selection)
}
inline ::std::string* PROTOBUF_NONNULL ValidateResponse::mutable_selection()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_selection();
  // @@protoc_insertion_point(field_mutable:specedge.ValidateResponse.selection)
  return _s;
}
inline const ::std::string& ValidateResponse::_internal_selection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selection_.Get();
}
inline void ValidateResponse::_internal_set_selection(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selection_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ValidateResponse::_internal_mutable_selection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.selection_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ValidateResponse::release_selection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:specedge.ValidateResponse.selection)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.selection_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.selection_.Set("", GetArena());
  }
  return released;
}
inline void ValidateResponse::set_allocated_selection(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.selection_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.selection_.IsDefault()) {
    _impl_.selection_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:specedge.ValidateResponse.selection)
}

// int32 prefill = 2;
inline void ValidateResponse::clear_prefill() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefill_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int32_t ValidateResponse::prefill() const {
  // @@protoc_insertion_point(field_get:specedge.ValidateResponse.prefill)
  return _internal_prefill();
}
inline void ValidateResponse::set_prefill(::int32_t value) {
  _internal_set_prefill(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:specedge.ValidateResponse.prefill)
}
inline ::int32_t ValidateResponse::_internal_prefill() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prefill_;
}
inline void ValidateResponse::_internal_set_prefill(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefill_ = value;
}

// -------------------------------------------------------------------

// SyncRequest

// -------------------------------------------------------------------

// SyncResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace specedge


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // specedge_2eproto_2epb_2eh
