// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: specedge.proto

#include "specedge.pb.h"
#include "specedge.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace specedge {

static const char* SpecEdgeService_method_names[] = {
  "/specedge.SpecEdgeService/Validate",
  "/specedge.SpecEdgeService/Sync",
};

std::unique_ptr< SpecEdgeService::Stub> SpecEdgeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SpecEdgeService::Stub> stub(new SpecEdgeService::Stub(channel, options));
  return stub;
}

SpecEdgeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Validate_(SpecEdgeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sync_(SpecEdgeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SpecEdgeService::Stub::Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::specedge::ValidateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::specedge::ValidateRequest, ::specedge::ValidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Validate_, context, request, response);
}

void SpecEdgeService::Stub::async::Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::specedge::ValidateRequest, ::specedge::ValidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Validate_, context, request, response, std::move(f));
}

void SpecEdgeService::Stub::async::Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Validate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>* SpecEdgeService::Stub::PrepareAsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::specedge::ValidateResponse, ::specedge::ValidateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Validate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>* SpecEdgeService::Stub::AsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SpecEdgeService::Stub::Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::specedge::SyncResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::specedge::SyncRequest, ::specedge::SyncResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sync_, context, request, response);
}

void SpecEdgeService::Stub::async::Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::specedge::SyncRequest, ::specedge::SyncResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, std::move(f));
}

void SpecEdgeService::Stub::async::Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>* SpecEdgeService::Stub::PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::specedge::SyncResponse, ::specedge::SyncRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>* SpecEdgeService::Stub::AsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

SpecEdgeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpecEdgeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SpecEdgeService::Service, ::specedge::ValidateRequest, ::specedge::ValidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SpecEdgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::specedge::ValidateRequest* req,
             ::specedge::ValidateResponse* resp) {
               return service->Validate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SpecEdgeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SpecEdgeService::Service, ::specedge::SyncRequest, ::specedge::SyncResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SpecEdgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::specedge::SyncRequest* req,
             ::specedge::SyncResponse* resp) {
               return service->Sync(ctx, req, resp);
             }, this)));
}

SpecEdgeService::Service::~Service() {
}

::grpc::Status SpecEdgeService::Service::Validate(::grpc::ServerContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SpecEdgeService::Service::Sync(::grpc::ServerContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace specedge
#include <grpcpp/ports_undef.inc>

