// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: specedge.proto
#ifndef GRPC_specedge_2eproto__INCLUDED
#define GRPC_specedge_2eproto__INCLUDED

#include "specedge.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace specedge {

class SpecEdgeService final {
 public:
  static constexpr char const* service_full_name() {
    return "specedge.SpecEdgeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::specedge::ValidateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>> AsyncValidate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>>(AsyncValidateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>> PrepareAsyncValidate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>>(PrepareAsyncValidateRaw(context, request, cq));
    }
    virtual ::grpc::Status Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::specedge::SyncResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>> AsyncSync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>>(AsyncSyncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>> PrepareAsyncSync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>>(PrepareAsyncSyncRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>* AsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specedge::ValidateResponse>* PrepareAsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>* AsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::specedge::SyncResponse>* PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::specedge::ValidateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>> AsyncValidate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>>(AsyncValidateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>> PrepareAsyncValidate(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>>(PrepareAsyncValidateRaw(context, request, cq));
    }
    ::grpc::Status Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::specedge::SyncResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>> AsyncSync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>>(AsyncSyncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>> PrepareAsyncSync(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>>(PrepareAsyncSyncRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, std::function<void(::grpc::Status)>) override;
      void Validate(::grpc::ClientContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, std::function<void(::grpc::Status)>) override;
      void Sync(::grpc::ClientContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>* AsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::specedge::ValidateResponse>* PrepareAsyncValidateRaw(::grpc::ClientContext* context, const ::specedge::ValidateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>* AsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::specedge::SyncResponse>* PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::specedge::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Validate_;
    const ::grpc::internal::RpcMethod rpcmethod_Sync_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Validate(::grpc::ServerContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response);
    virtual ::grpc::Status Sync(::grpc::ServerContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Validate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidate(::grpc::ServerContext* context, ::specedge::ValidateRequest* request, ::grpc::ServerAsyncResponseWriter< ::specedge::ValidateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Sync() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSync(::grpc::ServerContext* context, ::specedge::SyncRequest* request, ::grpc::ServerAsyncResponseWriter< ::specedge::SyncResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Validate<WithAsyncMethod_Sync<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Validate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::specedge::ValidateRequest, ::specedge::ValidateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::specedge::ValidateRequest* request, ::specedge::ValidateResponse* response) { return this->Validate(context, request, response); }));}
    void SetMessageAllocatorFor_Validate(
        ::grpc::MessageAllocator< ::specedge::ValidateRequest, ::specedge::ValidateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::specedge::ValidateRequest, ::specedge::ValidateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Validate(
      ::grpc::CallbackServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Sync() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::specedge::SyncRequest, ::specedge::SyncResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::specedge::SyncRequest* request, ::specedge::SyncResponse* response) { return this->Sync(context, request, response); }));}
    void SetMessageAllocatorFor_Sync(
        ::grpc::MessageAllocator< ::specedge::SyncRequest, ::specedge::SyncResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::specedge::SyncRequest, ::specedge::SyncResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sync(
      ::grpc::CallbackServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Validate<WithCallbackMethod_Sync<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Validate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Sync() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Validate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestValidate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Sync() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSync(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Validate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Validate(context, request, response); }));
    }
    ~WithRawCallbackMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Validate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Sync() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Sync(context, request, response); }));
    }
    ~WithRawCallbackMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sync(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Validate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Validate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::specedge::ValidateRequest, ::specedge::ValidateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::specedge::ValidateRequest, ::specedge::ValidateResponse>* streamer) {
                       return this->StreamedValidate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Validate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Validate(::grpc::ServerContext* /*context*/, const ::specedge::ValidateRequest* /*request*/, ::specedge::ValidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedValidate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::specedge::ValidateRequest,::specedge::ValidateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Sync() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::specedge::SyncRequest, ::specedge::SyncResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::specedge::SyncRequest, ::specedge::SyncResponse>* streamer) {
                       return this->StreamedSync(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Sync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sync(::grpc::ServerContext* /*context*/, const ::specedge::SyncRequest* /*request*/, ::specedge::SyncResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSync(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::specedge::SyncRequest,::specedge::SyncResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Validate<WithStreamedUnaryMethod_Sync<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Validate<WithStreamedUnaryMethod_Sync<Service > > StreamedService;
};

}  // namespace specedge


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_specedge_2eproto__INCLUDED
